start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout tiles horizontal horizontal'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-cmd-shift-ctrl-h = 'focus left'
alt-cmd-shift-ctrl-j = 'focus down'
alt-cmd-shift-ctrl-k = 'focus up'
alt-cmd-shift-ctrl-l = 'focus right'

alt-cmd-shift-ctrl-up = 'resize smart -100'
alt-cmd-shift-ctrl-down = 'resize smart +100'

# specific app config 
alt-cmd-shift-ctrl-a = 'workspace A'
alt-cmd-shift-ctrl-q = 'workspace Q'
alt-cmd-shift-ctrl-w = 'workspace W'
alt-cmd-shift-ctrl-s = 'workspace S'
alt-cmd-shift-ctrl-d = 'workspace D'


[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace W'
  
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace Q'


[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace D'

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace F'

# zathura 
[[on-window-detected]]
if.app-id = 'NULL-APP-BUNDLE-ID'
if.app-name-regex-substring = 'Users'
if.window-title-regex-substring = 'Users'
run = 'move-node-to-workspace P'
